name: push-tests
run-name: Test all valid suites

on: 
  pull_request:
  push:
    branches:
      - 'main'
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

jobs:
  check-all-valid:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout pytket_benchmarking
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.PYTKET_BENCHMARKING_DEPLOY_KEY }}
          repository: CQCL/pytket-benchmarking

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install pytket_benchmarking
        run: pip install .

      - name: Checkout pytket_benchmarking_store
        uses: actions/checkout@v4

      - name: Check all can upload
        run: python tests/all_can_upload.py
