name: push-tests
run-name: Push Tests
on: [push]
jobs:
  check-all-valid:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo hi there
      - run: |
        eval `ssh-agent -s`
        ssh-add - <<< '${{ secrets.PYTKET_BENCHMARKING_DEPLOY_KEY }}'
      - run: git clone git@github.com:CQCL/pytket-benchmarking.git
