name: push-tests
run-name: Push Tests
on: [push, pull_request]
jobs:
  check-all-valid:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout pytket_benchmarking
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.PYTKET_BENCHMARKING_DEPLOY_KEY }}
          repository: CQCL/pytket-benchmarking

      - name: Install pytket_benchmarking
        run: pip install .

      - name: Checkout pytket_benchmarking_store
        uses: actions/checkout@v4
